export const SCREENS = {
  LOGIN: "Login",
  HOME: "Home",
  CREATE_ORDER: "Create Purchase Order",
  VIEW_ORDER: "View Purchase Order",
  DETAILS_ORDER: "Details of the Purchase Order",
  DRAFTS_ORDER: "Drafts Orders",
  RETURN_ORDER: "Return Orders",
  DELIVERED_ORDER: "Delivered Purchase Orders",
  SUPPLIER_HOME: "Dashboard",
  INCOMING_ORDER: "Incoming Orders",
  SUPPLIER_ORDER_DETAILS: "Order Details",
  SUPPLIER_DELIVERED_ORDER: "Delivered Orders",
  SUPPLIER_ITEMS: "My Items",
  PAYMENTS_RECEIVED: "Payments Received",
  RETURN_REQUESTS: "Return Requests",
  RETURN_REQUESTS_DETAILS: "Return Request Details",
  PAYMENTS_RECEIVED_DETAILS: "Payment Received Details",
  SUBMIT_INVOICE: "SUBMIT_INVOICE",
};
